name: Metrics
on:
  # Schedule daily updates
  schedule: [{ cron: "0 0 * * 2,6" }]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - name: Waka Readme
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.METRICS_TOKEN }}
          SHOW_PROFILE_VIEWS: False
          SHOW_SHORT_INFO: False
          SHOW_LOC_CHART: False
          SHOW_COMMIT: False
          SHOW_DAYS_OF_WEEK: False
          SYMBOL_VERSION: 2
