name: My Profile
on:
  # Schedule daily updates
  schedule:
    - cron: "0 0 * * 0"
jobs:
  readme:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - name: Waka Readme
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.METRICS_TOKEN }}
          SHOW_PROFILE_VIEWS: False
          SHOW_EDITORS: False
          SHOW_SHORT_INFO: False
          SHOW_LOC_CHART: False
          SHOW_COMMIT: False
          SYMBOL_VERSION: 2
